---
linters:
  enable:
    # Default linters (just to make them explicit):
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Optional linters:
    - bodyclose
    - bidichk
    - containedctx
    - contextcheck
    - errname
    - errorlint
    - forbidigo
    - gci
    - gocritic
    - godot
    - gofmt
    - gosec
    - lll
    - misspell
    - noctx
    - reassign
    - revive
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true

  gci:
    sections:
      - standard
      - prefix(github.com/tobiassjosten/nogfx)
      - default
    custom-order: true

  gocritic:
    enabled-checks:
      - appendAssign
      - argOrder
      - badCall
      - badCond
      - badLock
      - badRegexp
      - badSorting
      - builtinShadow
      - builtinShadowDecl
      - caseOrder
      - codegenComment
      - commentedOutCode
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - exitAfterDefer
      - filepathJoin
      - flagDeref
      - flagName
      - mapKey
      - offBy1
      - sloppyLen
      - sloppyTypeAssert
      - sortSlice
      - sprintfQuotedString
      - syncMapLoadAndDelete
      - truncateCmp
      - uncheckedInlineErr
      - unnecessaryDefer
      - weakCond
    # @todo Figure out why this isn't accepted in GitHub Actions.
    # settings:
    #   commentedOutCode:
    #     minLength: 5

  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'

  revive:
    rules:
      # @todo Enable when we have time to clean up the violations.
      # - name: add-constant
      #   arguments:
      #     - allowInts: "0,1"
      #       allowStrs: '""'
      - name: atomic
      - name: blank-imports
      - name: bool-literal-in-expr
      # @todo Enable when we have time to clean up the violations.
      # - name: cognitive-complexity
      #   arguments: [7]
      - name: comment-spacings
      - name: confusing-naming
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
        arguments:
          - allowTypesBefore: "*testing.T,*github.com/user/repo/testing.Harness"
      - name: context-keys-type
      # @todo Enable when we have time to clean up the violations.
      # - name: cyclomatic
      #   arguments: [3]
      - name: datarace
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: enforce-map-style
        arguments:
          - literal
      # @todo Figure out why this isn't accepted in GitHub Actions.
      # - name: enforce-slice-style
      #   arguments:
      #     - literal
      - name: exported
      - name: flag-parameter
      - name: identical-branches
      - name: if-return
      - name: import-shadowing
      - name: increment-decrement
      - name: indent-error-flow
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: nested-structs
      - name: optimize-operands-order
      - name: package-comments
      - name: range-val-address
      - name: range-val-in-closure
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: redundant-import-alias
      - name: string-of-int
      - name: time-equal
      - name: time-naming
      - name: unchecked-type-assertion
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unhandled-error
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: use-any
      - name: useless-break
      - name: var-declaration
      - name: var-naming
      - name: waitgroup-by-value

run:
  go: '1.21'
  skip-dirs:
    - '^([a-zA-Z0-9\.-]+\/)*mocks?(\/|$)'
