---
builds:
  - dir: cmd/nogfx
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    ldflags:
      - -s -w -X pkg.Version={{ .Version }}

brews:
  - name: nogfx
    license: "MIT"
    tap:
      owner: tobiassjosten
      name: homebrew-nogfx
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    url_template: >-
      https://github.com/tobiassjosten/nogfx/releases/download/{{ .Tag }}
      /{{ .ArtifactName }}
    commit_msg_template: "Update brew formula: {{ .ProjectName }} {{ .Tag }}"
    commit_author:
      name: "{{ .Env.GORELEASER_COMMIT_NAME }}"
      email: "{{ .Env.GORELEASER_COMMIT_EMAIL }}"
