---
env:
  GH_URL=https://github.com/tobiassjosten/nogfx
  GH_DL_PATH=releases/download/{{ .Tag }}/{{ .ArtifactName }}

builds:
  - dir: cmd/nogfx
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    hooks:
      post:
       - upx --brute "{{ .Path }}"

brews:
  - name: nogfx
    license: "MIT"
    tap:
      owner: tobiassjosten
      name: homebrew-nogfx
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    url_template: "{{ .Env.GH_URL }}/{{ .Env.GH_DL_PATH }}"
    commit_msg_template: "Update brew formula: {{ .ProjectName }} {{ .Tag }}"
    commit_author:
      name: "{{ .Env.GORELEASER_COMMIT_NAME }}"
      email: "{{ .Env.GORELEASER_COMMIT_EMAIL }}"
