---
name: Pre-release

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release please
    runs-on: ubuntu-latest

    steps:
      - name:
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GH_PAT }}
          release-type: go
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          include-v-in-tag: false
          skip-labeling: true
