---
name: Quality assurance

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

jobs:
  lint-commits:
    name: Lint commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Verify commit messages
        uses: webiny/action-conventional-commits@v1.1.0

  lint-yaml:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check YAML formatting
        uses: ibiqlik/action-yamllint@v3

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download

      - name: Analyze Go code
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true

  test:
    name: Test code
    needs: [lint]
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download

      - name: Test Go code
        run: go test --coverprofile=coverage.out ./...

      - name: Trim coverage report
        run: cat coverage.out | grep -v "_mock.go" > coverage_trimmed.out

      - name: Upload to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: coverage_trimmed.out
          language: go
          force-coverage-parser: go
