name: Quality assurance

on:
  pull_request:
    branches: [main]

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check formatting
        run: |
          GOFMT_OUTPUT="$(gofmt -l -e .)"
          if [ -n "$GOFMT_OUTPUT" ]; then
            echo "The following code is not correctly formatted:"
            echo "${GOFMT_OUTPUT}"
            exit 1
          fi

      - name: Analyze Go code
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
          skip-go-installation: true
          skip-pkg-cache: true

  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install dependencies
        run: go mod download

      - name: Test Go code
        run: go test --coverprofile=coverage.out ./...

      - name: Upload to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: coverage.out
          language: go
          force-coverage-parser: go
