---
name: TODOs to issues

on: # yamllint disable-line rule:truthy
  push:
    # branches: [main]
  workflow_dispatch:
    inputs:
      importAll:
        default: 'false'
        required: false
        type: boolean
        description: Enable, if you want to import all TODOs. Runs on checked out branch! Only use if you're sure what you are doing.


permissions:
  issues: write
  repository-projects: read
  contents: read

jobs:
  todoissues:
    name: Synchronize issues
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Convert TODOs
        uses: derjuulsn/todo-issue@main
        with:
          autoAssign: false
          keywords: '@todo'
          caseSensitive: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
